# podmonitors.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rollouts-demo-sidecars
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["demo"]
  selector:
    matchLabels:
      app: rollouts-demo
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-ingressgateway
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["istio-system"]
  selector:
    matchLabels:
      istio: ingressgateway
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s