apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollouts-demo.fullname" . }}-stable
  labels:
    {{- include "rollouts-demo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "rollouts-demo.name" . }}
