apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: {{ .Release.Namespace }}
spec:
  metrics:
    - name: http-success-rate
      interval: 30s
      count: 3
      successCondition: result[0] >= 0.95
      failureLimit: 1
      provider:
        prometheus:
          address: http://promstack-kube-prometheus-prometheus.monitoring:9090
          query: |
            sum(rate(istio_requests_total{reporter="destination",destination_service=~"{{ include "rollouts-demo.fullname" . }}-(stable|canary).{{ .Release.Namespace }}.svc.cluster.local",response_code!~"5.."}[1m]))
            /
            sum(rate(istio_requests_total{reporter="destination",destination_service=~"{{ include "rollouts-demo.fullname" . }}-(stable|canary).{{ .Release.Namespace }}.svc.cluster.local"}[1m]))
