apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: {{ .Release.Namespace }}
spec:
  metrics:
    - name: http-success-rate
      initialDelay: 45s
      interval: 30s
      count: 4
      inconclusiveLimit: 3
      failureLimit: 1
      # Guard against empty results
      successCondition: len(result) > 0 && result[0] >= 0.95
      failureCondition: len(result) > 0 && result[0] < 0.80
      provider:
        prometheus:
          address: http://promstack-kube-prometheus-prometheus.monitoring:9090
          query: |
            (
              sum(rate(istio_requests_total{
                reporter="destination",
                destination_workload_namespace="{{ .Release.Namespace }}",
                response_code!~"5.."
              }[1m]))
            )
            /
            clamp_min(
              sum(rate(istio_requests_total{
                reporter="destination",
                destination_workload_namespace="{{ .Release.Namespace }}"
              }[1m])), 1e-9)
