apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: {{ .Values.gateway.port }}
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.gateway.host | default "*" | quote }}
