apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app/nginx
    repoURL: https://github.com/r0c1nante/gitOpsPlayGround.git
    targetRevision: HEAD
    



